ask_question:                     2
delete_question:                  0
answer_question:                  2
delete_answer:                   -3
close_question:                   1
reopen_question:                  0
comment_question:                 0
comment_answer:                   0
answer_picked_as_solution:       15
answer_unpicked_as_solution:    -15
vote_up_question:                 0
undo_vote_up_question:            0
vote_down_question:              -1
undo_vote_down_question:          1
question_receives_up_vote:        2
question_undo_up_vote:           -2
question_receives_down_vote:     -1
question_undo_down_vote:          1
vote_up_answer:                   0
undo_vote_up_answer:              0
vote_down_answer:                -1
undo_vote_down_answer:            1
answer_receives_up_vote:          2
answer_undo_up_vote:             -2
answer_receives_down_vote:       -1
answer_undo_down_vote:            1
day_with_activity:                0
day_without_activity:             0
